# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{nestegg}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John D. Hume"]
  s.date = %q{2009-09-22}
  s.description = %q{Module to add a 'cause' field to exceptions and automatically chains exceptions on re-raise}
  s.email = %q{duelin dot markers at gmail}
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    "History.txt",
     "License.txt",
     "Manifest.txt",
     "README.txt",
     "Rakefile",
     "VERSION",
     "examples/nestegg_example.rb",
     "lib/nestegg.rb",
     "lib/nestegg/nesting_exception.rb",
     "lib/nestegg/version.rb",
     "nestegg.gemspec",
     "spec/nestegg/nesting_exception_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://nestegg.rubyforge.org}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Nested exceptions for ruby}
  s.test_files = [
    "spec/nestegg/nesting_exception_spec.rb",
     "spec/spec_helper.rb",
     "examples/nestegg_example.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
